### ISSUE TITLE
Top-level dependency error

### ISSUE THREAD

**Issue by vicente000** [VeliovGroup/Meteor-UIBlocker#2]
In METEOR@1.3.4.4 I tried to install whit meteor add ostrio:uiblocker. Console launch error:

> > While selecting package versions:
> > error: Potentially incompatible change required to top-level dependency: themeteorchef:bert 1.1.0, was 2.1.0.
> > Constraints on package "themeteorchef:bert": 
> > I have themeteorchef:bert@2.1.0 version.
> > Any solution?

**Comment by dr-dimitru** [comment]
What if you will run `meteor update --allow-incompatible-update` before adding `ostrio:uiblocker` package?

> themeteorchef:bert

This package has no such dependencies, see: https://github.com/VeliovGroup/Meteor-UIBlocker/blob/master/package.js

**Comment by vicente000** [comment]
I tried to run meteor update --allow-incompatible-update before to add package. Console show same error.

**Comment by dr-dimitru** [comment]
Hi @vicente000 ,

Please update to [v2.0.1](https://github.com/VeliovGroup/Meteor-UIBlocker/releases/tag/2.0.1) your issue should be fixed.

Please check on your end, and let me know how it works.

**Comment by vicente000** [comment]
Solved! now it works correctly. Thank you

**Comment by dr-dimitru** [comment]
@vicente000 you're welcome.
Please support this project by starring on both GitHub and [atmosphere](https://atmospherejs.com/ostrio/uiblocker)
