### ISSUE TITLE
Semantic UI Version

### ISSUE THREAD

**Issue by tripflex** [VeliovGroup/Meteor-UIBlocker#3]
Thanks for creating this, I forked this to create a version for Semantic UI, which you can find here:
https://atmospherejs.com/tripflex/suiblocker
https://github.com/tripflex/meteor-suiblocker

**Comment by dr-dimitru** [comment]
Hello @tripflex ,

Thank you for the great fork, added to the docs - https://github.com/VeliovGroup/Meteor-UIBlocker/commit/b5eababdfbb88ecff6bd1c5803c9c8f054a74617
